# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Fair Launch'
  link: '/fair-launch'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
