# Sidebar navigation

# - label: 'Introduction'
#   link: '/'
- label: 'Fair Launch'
  link: '/fair-launch/'
- label: 'Tokenomics'
  link: '/tokenomics/'
- label: Features
  items:
    - label: 'Auto Farming'
      link: '/auto-farming/'
    - label: 'Auto Staking'
      link: '/auto-staking/'
    - label: 'No Whale'
      link: '/no-whale/'
    - label: 'Transaction Tax'
      link: '/transaction-tax/'
    - label: 'Automatic LP'
      link: '/automatic-lp/'
- label: More
  items:
    - label: 'FAQ'
      link: '/faq/'
    - label: 'Website'
      link: https://pepe.community
    - label: 'FrogBank'
      link: https://frogbank.pepe.community/
    - label: 'Telegram'
      link: https://t.me/PEPEcommunity
    - label: 'Twitter'
      link: https://twitter.com/pepe_community
